version: "3.9"
services:
  aprsc:
    build:
      context: .
      dockerfile: aprsc.dockerfile
    ports:
      - "10152:10152"
      - "14580:14580"
      - "10155:10155"
      - "14501:14501"
    volumes:
      - $PWD/config/aprsc.conf:/opt/aprsc/etc/aprsc.conf

  collector:
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    depends_on:
      - "db"
      - "aprsc"

  websocket:
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    ports:
      - "9000:9000"
    depends_on:
      - "db"
      - "aprsc"

  web:
    build:
      context: .
      dockerfile: trackdirect-apache.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
      - $PWD/heatmaps:/root/trackdirect/htdocs/public/heatmaps
    ports:
      - "80:80"
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - $PWD/db:/var/lib/postgresql/data
