version: "3.9"
services:
  aprsc:
    image: peterus/aprsc:latest
    restart: always
    ports:
      - "10152:10152"
      - "14580:14580"
      - "10155:10155"
      - "14501:14501"
    volumes:
      - $PWD/config/aprsc.conf:/opt/aprsc/etc/aprsc.conf

  collector:
    image: peterus/trackdirect-python:latest
    restart: always
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    depends_on:
      - "db"
      - "aprsc"

  websocket:
    image: peterus/trackdirect-python:latest
    restart: always
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    ports:
      - "9000:9000"
    depends_on:
      - "db"
      - "aprsc"

  web:
    image: peterus/trackdirect-apache:latest
    restart: always
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
      - $PWD/heatmaps:/root/trackdirect/htdocs/public/heatmaps
    ports:
      - "80:80"
    depends_on:
      - "db"

  db:
    image: peterus/trackdirect-db:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - $PWD/db:/var/lib/postgresql/data
